# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(auto_now=True)),
                ('prompt', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('src_files', models.CharField(max_length=2000)),
                ('result', models.CharField(max_length=2000)),
                ('language', models.CharField(max_length=2000)),
                ('assigment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.Assignment')),
            ],
        ),
    ]
