# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('prompt', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cmd', models.CharField(max_length=100)),
                ('max_exec_time', models.IntegerField()),
                ('max_mem_usage_KB', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('src_files', models.CharField(max_length=2000)),
                ('main_file', models.CharField(max_length=100, null=True)),
                ('result', models.CharField(max_length=2000)),
                ('complete', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.Assignment')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.Language')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.Language'),
        ),
    ]
