# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_auto_20170326_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='language',
            field=models.CharField(choices=[('Python', 'python'), ('Java', 'java'), ('C', 'C')], max_length=20),
        ),
    ]
