# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0003_auto_20170326_0325'),
        ('submit', '0003_auto_20170326_0252'),
    ]

    operations = [
    ]
